/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2022-11-11 12:49:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Connection;
import java.util.List;
import com.videoCtrl.Profile;

public final class profile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar", Long.valueOf(1667798975077L));
    _jspx_dependants.put("jar:file:/C:/Users/vihin/Desktop/Project/Project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Vid/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar!/META-INF/c.tld", Long.valueOf(1602854172000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.sql.Statement");
    _jspx_imports_classes.add("java.sql.DriverManager");
    _jspx_imports_classes.add("com.videoCtrl.Profile");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

String id = request.getParameter("userId");
String driverName = "com.mysql.jdbc.Driver";
String connectionUrl = "jdbc:mysql://localhost:3306/";
String dbName = "video_db";
String userId = "root";
String password = "200103003074";


try {
Class.forName(driverName);
} catch (ClassNotFoundException e) {
e.printStackTrace();
}

Connection connection = null;
Statement statement = null;
ResultSet resultSet = null;

      out.write("\r\n");
      out.write("    \r\n");
 HttpSession se = request.getSession(true);
	String str = se.getAttribute("username").toString();
	String str1 = se.getAttribute("username1").toString();

      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <title>Profile</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./styles/style.css\">\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi\" crossorigin=\"anonymous\">\r\n");
      out.write("  	<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css\">\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("  	\r\n");
      out.write("  	\r\n");
      out.write("  	<div class=\"container-fluid text-center bg-light top-header g-0\">\r\n");
      out.write("	  <div class=\"main-header row align-items-center d-flex flex-wrap\">\r\n");
      out.write("	    <div class=\"col-12 col-lg-2 justify-content-center order-1\">\r\n");
      out.write("	      <a href=\"./index.jsp\" class=\"navbar-brand\">\r\n");
      out.write("	      	<img src=\"./img/logo.jpg\" class=\"img-fluid\" style=\"width:70px;\" alt=\"...\">\r\n");
      out.write("	      </a>\r\n");
      out.write("	    </div>\r\n");
      out.write("	    <div class=\"col-12 col-lg-7 order-lg-2 order-3 my-3\">\r\n");
      out.write("	      <form class=\"d-flex\" role=\"search\">\r\n");
      out.write("	        <input class=\"form-control me-2 py-1\" type=\"search\" placeholder=\"Search\" aria-label=\"Search\">\r\n");
      out.write("	        <button class=\"btn text-light\" style=\"background:#394339;\" type=\"submit\">Search</button>\r\n");
      out.write("	      </form>\r\n");
      out.write("	    </div>\r\n");
      out.write("	    <div class=\"col-12 col-lg-3 order-lg-3 order-2 d-none d-lg-block\">\r\n");
      out.write("	    	<div class=\"row\">\r\n");
      out.write("		    <div class=\"col\">\r\n");
      out.write("		      <a href=\"./library.jsp\"  class=\"btn\" style=\"background:var(--clr-1); color:var(--clr-5);\">\r\n");
      out.write("		      	<span>Watch History</span>\r\n");
      out.write("		      </a>\r\n");
      out.write("		      <a href=\"./accounts.jsp\" class=\"btn\" style=\"background:var(--clr-1); color:var(--clr-5);\">\r\n");
      out.write("		      	<span>Sign Out</span>\r\n");
      out.write("		      </a>\r\n");
      out.write("		    </div>\r\n");
      out.write("		  </div>\r\n");
      out.write("	    </div>\r\n");
      out.write("	  </div>\r\n");
      out.write("	  \r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	");

	  		
	  		try{
	  			connection = DriverManager.getConnection(connectionUrl+dbName, userId, password);
	  			statement=connection.createStatement();
	  			String getSearch = request.getParameter("search");
	  			String sqlQ; 
	  			
	  			
	  			sqlQ ="select * from profile where UserName='"+str1+"'";
	  			
	  			
	  			resultSet = statement.executeQuery(sqlQ);
	  			while(resultSet.next()){
	  				
      out.write("\r\n");
      out.write("	  				");
 String u = resultSet.getString("UserName");
      out.write("\r\n");
      out.write("	  				");
 String f = resultSet.getString("fName");
      out.write("\r\n");
      out.write("	  				");
 String l = resultSet.getString("lName");
      out.write("\r\n");
      out.write("	  				");
 String e = resultSet.getString("email");
      out.write("\r\n");
      out.write("	  				\r\n");
      out.write("	  					<div class=\"row m-5\" style=\" display:flex; justify-content:center; margin-left:20rem;\">\r\n");
      out.write("						  	<div class=\"col-12 pb-5\">\r\n");
      out.write("						    	<div class=\"row pb-5\">\r\n");
      out.write("						    		<div class=\"col-6\">\r\n");
      out.write("						    			<span class=\"h4\" style=\"color:var(--clr-1);\">First Name: ");
      out.print(resultSet.getString("fName") );
      out.write("</span>\r\n");
      out.write("						    		</div>\r\n");
      out.write("						    		<div class=\"col-6\">\r\n");
      out.write("						    		\r\n");
      out.write("						    			<button type=\"button\" class=\"btn ms-5\" style=\"background:var(--clr-1); color:var(--clr-5);\" data-bs-toggle=\"modal\" data-bs-target=\"#m1\">\r\n");
      out.write("										  Edit First Name\r\n");
      out.write("									  </button>\r\n");
      out.write("						    		</div>\r\n");
      out.write("						    	</div>\r\n");
      out.write("						    	<div class=\"row pb-5\">\r\n");
      out.write("						    		<div class=\"col-6\">\r\n");
      out.write("						    			<span class=\"h4\" style=\"color:var(--clr-1);\">Last Name: ");
      out.print(resultSet.getString("lName") );
      out.write("</span>\r\n");
      out.write("						    		</div>\r\n");
      out.write("						    		<div class=\"col-6\">\r\n");
      out.write("						    		\r\n");
      out.write("						    			<button type=\"button\" class=\"btn ms-5\" style=\"background:var(--clr-1); color:var(--clr-5);\" data-bs-toggle=\"modal\" data-bs-target=\"#m2\">\r\n");
      out.write("										  Edit Last Name\r\n");
      out.write("									  </button>\r\n");
      out.write("						    		</div>\r\n");
      out.write("						    	</div>\r\n");
      out.write("						    	<div class=\"row pb-5\">\r\n");
      out.write("						    		<div class=\"col-6\">\r\n");
      out.write("						    			<span class=\"h4\" style=\"color:var(--clr-1);\">Email: ");
      out.print(resultSet.getString("email") );
      out.write("</span>\r\n");
      out.write("						    		</div>\r\n");
      out.write("						    		<div class=\"col-6\">\r\n");
      out.write("						    		\r\n");
      out.write("						    			<button type=\"button\" class=\"btn ms-5\" style=\"background:var(--clr-1); color:var(--clr-5);\" data-bs-toggle=\"modal\" data-bs-target=\"#m3\">\r\n");
      out.write("										  Edit Email\r\n");
      out.write("									  </button>\r\n");
      out.write("						    		</div>\r\n");
      out.write("						    	</div>\r\n");
      out.write("						    </div>\r\n");
      out.write("					    </div>\r\n");
      out.write("	  		\r\n");
      out.write("	  			<div class=\"col-12\">\r\n");
      out.write("	    	<div class=\"row\">\r\n");
      out.write("	    		<div class=\"col-12\">\r\n");
      out.write("	    			<button type=\"button\" class=\"btn ms-5\" style=\"background:var(--clr-1); color:var(--clr-5);\" data-bs-toggle=\"modal\" data-bs-target=\"#deleteAccount\">\r\n");
      out.write("					  Delete Account\r\n");
      out.write("				  </button>\r\n");
      out.write("	    		</div>\r\n");
      out.write("	    	</div>\r\n");
      out.write("	    </div>   \r\n");
      out.write("	    \r\n");
      out.write("	    \r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("	<!-- drop down -->\r\n");
      out.write("	<!-- edit first name -->\r\n");
      out.write("	<div class=\"modal fade\" id=\"m1\" tabindex=\"-1\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("	  <div class=\"modal-dialog\">\r\n");
      out.write("	    <div class=\"modal-content\">\r\n");
      out.write("	      <div class=\"modal-header\">\r\n");
      out.write("	        <h1 class=\"modal-title fs-5\" id=\"exampleModalLabel\">Edit First Name</h1>\r\n");
      out.write("	        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("	      </div>\r\n");
      out.write("	      <div class=\"modal-body\">\r\n");
      out.write("	        <form action=\"insertP\" method=\"post\">\r\n");
      out.write("	        	<div class=\"mb-3\">\r\n");
      out.write("				    <input type=\"text\" name=\"fin\" class=\"form-control\" id=\"exampleInputEmail1\" aria-describedby=\"emailHelp\" placeholder=\"Add new First Name\">\r\n");
      out.write("					<input type=\"text\" name=\"user\" value=\"");
      out.print(u);
      out.write("\" style=\"display:none;\">\r\n");
      out.write("				</div>\r\n");
      out.write("	        	<button type=\"submit\" class=\"btn text-light\" style=\"background:var(--clr-1)\">Update</button>\r\n");
      out.write("	        </form>\r\n");
      out.write("	      </div>\r\n");
      out.write("	    </div>\r\n");
      out.write("	  </div>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<!-- edit last name -->\r\n");
      out.write("		<div class=\"modal fade\" id=\"m2\" tabindex=\"-1\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("	  <div class=\"modal-dialog\">\r\n");
      out.write("	    <div class=\"modal-content\">\r\n");
      out.write("	      <div class=\"modal-header\">\r\n");
      out.write("	        <h1 class=\"modal-title fs-5\" id=\"exampleModalLabel\">Edit Last Name</h1>\r\n");
      out.write("	        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("	      </div>\r\n");
      out.write("	      <div class=\"modal-body\">\r\n");
      out.write("	        <form action=\"insertP1\" method=\"post\">\r\n");
      out.write("	        	<div class=\"mb-3\">\r\n");
      out.write("				    <input type=\"text\" name=\"lin\" class=\"form-control\" id=\"exampleInputEmail1\" aria-describedby=\"emailHelp\" placeholder=\"Add new Last Name\">\r\n");
      out.write("					<input type=\"text\" name=\"user\" value=\"");
      out.print(u);
      out.write("\" style=\"display:none;\">\r\n");
      out.write("				</div>\r\n");
      out.write("	        	<button type=\"submit\" class=\"btn text-light\" style=\"background:var(--clr-1)\">Update</button>\r\n");
      out.write("	        </form>\r\n");
      out.write("	      </div>\r\n");
      out.write("	    </div>\r\n");
      out.write("	  </div>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<!-- edit email -->\r\n");
      out.write("		<div class=\"modal fade\" id=\"m3\" tabindex=\"-1\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("	  <div class=\"modal-dialog\">\r\n");
      out.write("	    <div class=\"modal-content\">\r\n");
      out.write("	      <div class=\"modal-header\">\r\n");
      out.write("	        <h1 class=\"modal-title fs-5\" id=\"exampleModalLabel\">Edit Email</h1>\r\n");
      out.write("	        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("	      </div>\r\n");
      out.write("	      <div class=\"modal-body\">\r\n");
      out.write("	        <form action=\"insertP2\" method=\"post\">\r\n");
      out.write("	        	<div class=\"mb-3\">\r\n");
      out.write("				    <input type=\"text\" name=\"em\" class=\"form-control\" id=\"exampleInputEmail1\" aria-describedby=\"emailHelp\" placeholder=\"Add new Email\">\r\n");
      out.write("					<input type=\"text\" name=\"user\" value=\"");
      out.print(u);
      out.write("\" style=\"display:none;\">\r\n");
      out.write("				</div>\r\n");
      out.write("	        	<button type=\"submit\" class=\"btn text-light\" style=\"background:var(--clr-1)\">Update</button>\r\n");
      out.write("	        </form>\r\n");
      out.write("	      </div>\r\n");
      out.write("	    </div>\r\n");
      out.write("	  </div>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<!-- upload video -->\r\n");
      out.write("	<form action=\"upload\" method=\"post\">\r\n");
      out.write("	<div class=\"modal fade\" id=\"uploadVideo\" tabindex=\"-1\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("	  <div class=\"modal-dialog\">\r\n");
      out.write("	    <div class=\"modal-content\">\r\n");
      out.write("	      <div class=\"modal-header\">\r\n");
      out.write("	        <h1 class=\"modal-title fs-5\" id=\"exampleModalLabel\" style=\"color:var(--clr-1);\">Upload Video</h1>\r\n");
      out.write("	        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("	      </div>\r\n");
      out.write("	      <div class=\"mb-3\">\r\n");
      out.write("				    \r\n");
      out.write("  					<input class=\"form-control form-control-lg\" name=\"video\" type=\"file\">\r\n");
      out.write("	     </div>\r\n");
      out.write("	     <div class=\"mb-3\">\r\n");
      out.write("	     	<input type=\"text\" class=\"form-control\" name=\"user\" aria-describedby=\"emailHelp\" value=\"");
      out.print(str1);
      out.write("\">\r\n");
      out.write("				    <label for=\"exampleInputEmail1\" class=\"form-label\">Video Title</label>\r\n");
      out.write("				    <input type=\"text\" class=\"form-control\" name=\"videoTitle\" aria-describedby=\"emailHelp\">\r\n");
      out.write("	    </div>\r\n");
      out.write("				  <div class=\"mb-3\">\r\n");
      out.write("				    <label for=\"exampleInputEmail1\" class=\"form-label\">Video Description</label>\r\n");
      out.write("				    <input type=\"text\" class=\"form-control\" name=\"vdesc\" aria-describedby=\"emailHelp\">\r\n");
      out.write("				  </div>\r\n");
      out.write("	    \r\n");
      out.write("				  <div class=\"mb-3\">\r\n");
      out.write("				    <label for=\"exampleInputEmail1\" class=\"form-label\">Video Category</label>\r\n");
      out.write("				    <input type=\"text\" class=\"form-control\" name=\"vcategory\" aria-describedby=\"emailHelp\">\r\n");
      out.write("				  </div>\r\n");
      out.write("				  <button type=\"submit\" class=\"btn\" style=\"background:var(--clr-1); color:var(--clr-5);\">Confirm and Upload</button>\r\n");
      out.write("	    </div>\r\n");
      out.write("	  </div>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	</form>\r\n");
      out.write("	\r\n");
      out.write("	");
 
	  		}
	  		}catch(Exception e){
	  			e.printStackTrace();
	  		}	
	  		
      out.write("\r\n");
      out.write("	 \r\n");
      out.write("	\r\n");
      out.write("	<!-- My Videos -->\r\n");
      out.write("	<div class=\"container text-center mt-3 mb-5\">\r\n");
      out.write("		<h2 style=\"color:var(--clr-1);\">My videos</h2>\r\n");
      out.write("		<div id=\"features\" class=\"container-fluid\">\r\n");
      out.write("	  	<div class=\"row\">\r\n");
      out.write("	  		\r\n");
      out.write("	  		");

	  		
	  		try{
	  			connection = DriverManager.getConnection(connectionUrl+dbName, userId, password);
	  			statement=connection.createStatement();
	  			String getSearch = request.getParameter("search");
	  			String sqlQ; 
	  			String user = str1;
	  			sqlQ ="select * from video where UserName='"+user+"'";
	  			
	  			resultSet = statement.executeQuery(sqlQ);
	  			while(resultSet.next()){
	  				
      out.write("\r\n");
      out.write("	  			\r\n");
      out.write("	  		<!-- upload video -->\r\n");
      out.write("	  		<div class=\"col-12 col-md-6 col-lg-3 my-3 mx-3\">\r\n");
      out.write("	  			<div class=\"card\" style=\"width: 18rem;\">\r\n");
      out.write("	  			  <div class=\"card-img\">\r\n");
      out.write("				  	<img src=\"./img/i1.jpg\" class=\"card-img-top\" alt=\"...\">\r\n");
      out.write("				  	<form action=\"getvid\" method=\"post\">\r\n");
      out.write("				  		<input type=\"text\" name=\"vid\" style=\"display:none;\" value=\"");
      out.print(resultSet.getInt("idvideo"));
      out.write("\">\r\n");
      out.write("				  		<input type=\"text\" name=\"wTime\" style=\"display:none;\" value=\"ht\" id=\"getDate\">\r\n");
      out.write("				  		<button type=\"submit\" class=\"btn play-btn\"><i class=\"bi bi-play-circle\"></i></button>\r\n");
      out.write("				  	</form>\r\n");
      out.write("				  	\r\n");
      out.write("				  </div>\r\n");
      out.write("				  <div class=\"card-body\">\r\n");
      out.write("				    <h5 class=\"card-title\">");
      out.print(resultSet.getString("vname"));
      out.write("</h5>\r\n");
      out.write("				    <p class=\"card-text\">");
      out.print(resultSet.getString("description"));
      out.write("</p>\r\n");
      out.write("				  </div>\r\n");
      out.write("				</div>\r\n");
      out.write("	  		</div>\r\n");
      out.write("	  		\r\n");
      out.write("	  		");
 
	  		}
	  		}catch(Exception e){
	  			e.printStackTrace();
	  		}	
	  		
      out.write("\r\n");
      out.write("	  </div>\r\n");
      out.write("	  \r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"col-12 pb-5\">\r\n");
      out.write("	    	<div class=\"row\">\r\n");
      out.write("	    		\r\n");
      out.write("	    		<div class=\"col-6\">\r\n");
      out.write("	    			<button type=\"button\" class=\"btn ms-5\" style=\"background:var(--clr-1); color:var(--clr-5);\" data-bs-toggle=\"modal\" data-bs-target=\"#uploadVideo\">\r\n");
      out.write("						  Upload Video\r\n");
      out.write("					  </button>\r\n");
      out.write("	    		</div>\r\n");
      out.write("	    	</div>\r\n");
      out.write("	    </div>\r\n");
      out.write("	\r\n");
      out.write("	  	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("  	\r\n");
      out.write("	\r\n");
      out.write("			\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<footer style=\"background:var(--clr-1);\" class=\"text-center py-4\">\r\n");
      out.write("		<a href=\"#\" class=\"btn text-light\">@watchita</a>\r\n");
      out.write("	</footer>\r\n");
      out.write("	\r\n");
      out.write("     <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("  	<script src=\"../JS/script.js\"></script>\r\n");
      out.write("  	<script>\r\n");
      out.write("	  		  	\r\n");
      out.write("	  	function getVideo(file1, file2){\r\n");
      out.write("	  		localStorage.setItem('vidURL', file1);\r\n");
      out.write("	  		localStorage.setItem('downURL', file2);\r\n");
      out.write("	  		window.location.href = \"./videoPlayer.jsp\";\r\n");
      out.write("	  	}\r\n");
      out.write("  	</script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
