/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2022-11-10 10:39:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Connection;
import javax.script.*;
import java.util.List;
import com.videoCtrl.Vid1;
import java.sql.*;

public final class videoPlayer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar", Long.valueOf(1667798975077L));
    _jspx_dependants.put("jar:file:/C:/Users/vihin/Desktop/Project/Project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Vid/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar!/META-INF/c.tld", Long.valueOf(1602854172000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_packages.add("javax.script");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.sql.Statement");
    _jspx_imports_classes.add("com.videoCtrl.Vid1");
    _jspx_imports_classes.add("java.sql.DriverManager");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

String id = request.getParameter("userId");
String driverName = "com.mysql.jdbc.Driver";
String connectionUrl = "jdbc:mysql://localhost:3306/";
String dbName = "video_db";
String userId = "root";
String password = "1234";


try {
Class.forName(driverName);
} catch (ClassNotFoundException e) {
e.printStackTrace();
}

Connection connection = null;
Statement statement = null;
ResultSet resultSet = null;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 List vid = (List)request.getAttribute("vids"); 
      out.write("\r\n");
      out.write("\r\n");
 HttpSession se = request.getSession(true);
	String str = se.getAttribute("username").toString();
	String str1 = se.getAttribute("username1").toString();

      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <title>Video Player</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./styles/style.css\">\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi\" crossorigin=\"anonymous\">\r\n");
      out.write("  	<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css\">\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("  	\r\n");
      out.write("  	<div class=\"container-fluid text-center bg-light top-header g-0\">\r\n");
      out.write("	  <div class=\"main-header row align-items-center d-flex flex-wrap\">\r\n");
      out.write("	    <div class=\"col-12 col-lg-2 justify-content-center order-1\">\r\n");
      out.write("	      <a href=\"./index.jsp\" class=\"navbar-brand\">\r\n");
      out.write("	      	<img src=\"./img/logo.jpg\" class=\"img-fluid\" style=\"width:70px;\" alt=\"...\">\r\n");
      out.write("	      </a>\r\n");
      out.write("	    </div>\r\n");
      out.write("	    <div class=\"col-12 col-lg-7 order-lg-2 order-3 my-3\">\r\n");
      out.write("	      <form class=\"d-flex\" role=\"search\">\r\n");
      out.write("	        <input class=\"form-control me-2 py-1\" type=\"search\" placeholder=\"Search\" aria-label=\"Search\">\r\n");
      out.write("	        <button class=\"btn text-light\" style=\"background:#394339;\" type=\"submit\">Search</button>\r\n");
      out.write("	      </form>\r\n");
      out.write("	    </div>\r\n");
      out.write("	    <div class=\"col-12 col-lg-3 order-lg-3 order-2 d-none d-lg-block\">\r\n");
      out.write("	    	<div class=\"row\">\r\n");
      out.write("		    <div class=\"col\">\r\n");
      out.write("		      <a href=\"./watchHistory.jsp\" target=\"_blank\" class=\"btn\" style=\"background:var(--clr-1); color:var(--clr-5);\">\r\n");
      out.write("		      	<i class=\"bi bi-collection\"></i>\r\n");
      out.write("		      	<span>Library</span>\r\n");
      out.write("		      </a>\r\n");
      out.write("		    </div>\r\n");
      out.write("		    <div class=\"col\">\r\n");
      out.write("		      <a href=\"./accounts.jsp\" target=\"_blank\" class=\"btn\" style=\"background:var(--clr-1); color:var(--clr-5);\">\r\n");
      out.write("		      	<span>");
      out.print(str);
      out.write("</span>\r\n");
      out.write("		      </a>\r\n");
      out.write("		    </div>\r\n");
      out.write("		  </div>\r\n");
      out.write("	    </div>\r\n");
      out.write("	  </div>\r\n");
      out.write("	  \r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"container-fluid w-100\">\r\n");
      out.write("	\r\n");
      out.write("		\r\n");
      out.write("	\r\n");
      out.write("		");
 Vid1 vid1 = (Vid1)vid.get(0); 
      out.write("\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("	  	<div class=\"videoPlayer\">\r\n");
      out.write("			<video width=\"100%\" height=\"500px\" controls autoplay id=\"myVideo\">\r\n");
      out.write("				<source src=\"");
      out.print(vid1.getVideo());
      out.write("\" type=\"video/mp4\">\r\n");
      out.write("			</video>				\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"row px-3\">\r\n");
      out.write("		    <div class=\"col-12 col-md-8\">\r\n");
      out.write("		      <h4 id=\"vidtitle\">");
      out.print(vid1.getVname());
      out.write("</h4>\r\n");
      out.write("		      <h5 class=\"fs-6\">\r\n");
      out.write("		      	<span>123 views.</span>\r\n");
      out.write("		      	<span>");
      out.print(vid1.getDate());
      out.write("</span>\r\n");
      out.write("		      </h5>\r\n");
      out.write("		    </div>\r\n");
      out.write("		    <div class=\"col-12 col-md-4 d-flex\">\r\n");
      out.write("		      <div class=\"d-flex align-items-center\">\r\n");
      out.write("		      	<form action=\"getLike\" method=\"post\">\r\n");
      out.write("		      	<button type=\"button\" class=\"btn fs-3 likeBtn\">\r\n");
      out.write("		      		<i class=\"bi bi-hand-thumbs-up\" id=\"likeBtn\"></i>\r\n");
      out.write("		      	</button>\r\n");
      out.write("		      	<span class=\"fs-5\" id=\"likeCount\">12</span>\r\n");
      out.write("		      	</form>\r\n");
      out.write("		      </div>\r\n");
      out.write("		      <div class=\"d-flex align-items-center\">\r\n");
      out.write("		      	<button type=\"button\" class=\"btn fs-3 dislikeBtn\">\r\n");
      out.write("		      		<i class=\"bi bi-hand-thumbs-down\"></i>\r\n");
      out.write("		      	</button>\r\n");
      out.write("		      	<span class=\"fs-5\" id=\"dislikeCount\">5</span>\r\n");
      out.write("		      </div>\r\n");
      out.write("		      <div class=\"d-flex align-items-center\">\r\n");
      out.write("		      	<a href=\"\" class=\"btn\" id=\"downBtn\">\r\n");
      out.write("		      		<i class=\"bi bi-arrow-down-circle-fill\"></i>\r\n");
      out.write("		      		<span class=\"fs-5\">Download</span>\r\n");
      out.write("		      	</a>\r\n");
      out.write("		      </div>\r\n");
      out.write("		      <div class=\"d-flex align-items-center\">\r\n");
      out.write("		      	<button type=\"button\" class=\"btn\">\r\n");
      out.write("		      		<i class=\"bi bi-plus-circle-fill\"></i>\r\n");
      out.write("		      		<span class=\"fs-5\">Save</span>\r\n");
      out.write("		      	</button>\r\n");
      out.write("		      </div>\r\n");
      out.write("		    </div>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		<div class=\"w-100 my-3\" style=\"background:var(--clr-1); height:2px;\"></div>\r\n");
      out.write("		\r\n");
      out.write("		<a href=\"./profile.jsp\" class=\"btn fs-5 d-flex align-items-center px-3\" onload=\"call()\">\r\n");
      out.write("			<i class=\"bi bi-person-circle fs-2\"></i>\r\n");
      out.write("			\r\n");
      out.write("			");

				try{			
				connection = DriverManager.getConnection(connectionUrl+dbName, userId, password);
  				statement=connection.createStatement();
  				String name = vid1.getUser();

  				
  	 				
  				
  				String sql = "select * from profile where UserName='"+name+"'";
  				resultSet = statement.executeQuery(sql);
	  			while(resultSet.next()){
	  			
      out.write("\r\n");
      out.write("	  			\r\n");
      out.write("	  				<span class=\"ps-2\" >");
      out.print(resultSet.getString(2));
      out.write(' ');
      out.print(resultSet.getString("lName"));
      out.write("</span>\r\n");
      out.write("	  			");

	  			}	
				}catch(Exception e){
					e.printStackTrace();
				}
	  		
      out.write("\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("		</a>\r\n");
      out.write("\r\n");
      out.write("		<p class=\"p-3\" id=\"desc\">");
      out.print(vid1.getDesc());
      out.write("</p>\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		<div class=\"w-100 my-3\" style=\"background:var(--clr-1); height:2px;\"></div>\r\n");
      out.write("		\r\n");
      out.write("		<div class=\"d-block px-3\">\r\n");
      out.write("			<h4 id=\"ccount\"></h4>\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			<form class=\"mb-3\" action=\"insert\" method=\"post\">\r\n");
      out.write("				<div class=\"mb-3\">\r\n");
      out.write("			   		<input type=\"text\" name=\"comment\" class=\"form-control border-top-0 border-start-0 border-end-0 border-bottom-1 cin\" placeholder=\"Add a comment\">\r\n");
      out.write("			  		<input type=\"text\" name=\"vidID\" id=\"vidID\" style=\"display:none;\" class=\"form-control border-top-0 border-start-0 border-end-0 border-bottom-1 cin\" placeholder=\"Add a comment\" value=\"");
      out.print(vid1.getVid());
      out.write("\">\r\n");
      out.write("			  		<input type=\"text\" name=\"userID\" id=\"vidID\" style=\"display:none;\" class=\"form-control border-top-0 border-start-0 border-end-0 border-bottom-1 cin\" placeholder=\"Add a comment\" value=\"");
      out.print(str1);
      out.write("\">	\r\n");
      out.write("			  	</div>\r\n");
      out.write("			  	<input type=\"submit\" class=\"btn\" style=\"background:var(--clr-1); color:var(--clr-5);\" onclick=\"addc()\" value=\"Comment\">\r\n");
      out.write("			</form>\r\n");
      out.write("			\r\n");
      out.write("			<ul id=\"cList\" class=\"list-group border-0 my-3 w-100\">\r\n");
      out.write("			\r\n");
      out.write("						");

							try{
								Class.forName("com.mysql.jdbc.Driver");
								Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/video_db","root", "1234");
								int vidid = vid1.getVid();

								String query = "select * from comment where videoID='"+vidid+"'";
								PreparedStatement ps = con.prepareStatement(query);
								ResultSet rs = ps.executeQuery(query);
								
								
								while(rs.next()){
								
      out.write("\r\n");
      out.write("								<li class=\"list-group-item border-start-0 border-end-0 border-top-0 pb-3 mb-3 d-flex w-100\">\r\n");
      out.write("									<i class=\"bi bi-person-circle fs-4\"></i>\r\n");
      out.write("									<span class=\"ps-3 fs-5\" style=\"width:70%;\">");
      out.print( rs.getString("comment"));
      out.write("</span>\r\n");
      out.write("									");

										String user1 = rs.getString("user");
										String user2 = str1;
										int user3 = rs.getInt("commentID");
										
										
										
										if(user1.equals(user2)){
      out.write("\r\n");
      out.write("											\r\n");
      out.write("											<div class=\"dropdown w-100 ms-5\" style=\"right:-40rem;\">\r\n");
      out.write("											  <button class=\"btn btn-secondary dropdown-toggle\" style=\"background:var(--clr-1);\"type=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\"></button>\r\n");
      out.write("											  <div class=\"dropdown-menu p-3\">\r\n");
      out.write("											    \r\n");
      out.write("											    	<button type=\"button\" class=\"btn text-light mb-3\" style=\"background:var(--clr-1); width:10rem;\" data-bs-toggle=\"modal\" data-bs-target=\"#exampleModal\">\r\n");
      out.write("													  Edit comment\r\n");
      out.write("													</button>\r\n");
      out.write("											    	<form action=\"deleteComment\" method=\"post\">\r\n");
      out.write("											    		<input type=\"text\" name=\"commentCD\" value=\"");
      out.print(user3);
      out.write("\" style=\"display:none;\">\r\n");
      out.write("														<input type=\"text\" name=\"userND\" value=\"");
      out.print(user2);
      out.write("\" style=\"display:none;\">\r\n");
      out.write("														<button type=\"submit\" class=\"btn text-light bg-danger\" style=\"width:10rem;\" data-bs-toggle=\"modal\" data-bs-target=\"#\">\r\n");
      out.write("														  Delete comment\r\n");
      out.write("														</button>\r\n");
      out.write("													</form>\r\n");
      out.write("											  </div>\r\n");
      out.write("											</div>\r\n");
      out.write("											\r\n");
      out.write("											\r\n");
      out.write("											\r\n");
      out.write("											\r\n");
      out.write("											\r\n");
      out.write("											<div class=\"modal fade\" id=\"exampleModal\" tabindex=\"-1\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("											  <div class=\"modal-dialog\">\r\n");
      out.write("											    <div class=\"modal-content\">\r\n");
      out.write("											      <div class=\"modal-header\">\r\n");
      out.write("											        <h1 class=\"modal-title fs-5\" id=\"exampleModalLabel\">Edit Comment</h1>\r\n");
      out.write("											        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("											      </div>\r\n");
      out.write("											      <div class=\"modal-body\">\r\n");
      out.write("											      	<form action=\"updateComment\" method=\"post\">\r\n");
      out.write("											        	<div class=\"mb-3\">\r\n");
      out.write("														    <input type=\"text\" name=\"commentE\" class=\"form-control\" id=\"exampleInputEmail1\" aria-describedby=\"emailHelp\" placeholder=\"Add new comment\">\r\n");
      out.write("															<input type=\"text\" name=\"userC\" value=\"");
      out.print(user2);
      out.write("\" style=\"display:none;\">\r\n");
      out.write("															<input type=\"text\" name=\"commentC\" value=\"");
      out.print(user3);
      out.write("\" style=\"display:none;\">\r\n");
      out.write("														</div>\r\n");
      out.write("											        	<button type=\"submit\" class=\"btn text-light\" style=\"background:var(--clr-1)\">Edit Comment</button>\r\n");
      out.write("											        </form>\r\n");
      out.write("											      </div>\r\n");
      out.write("											    </div>\r\n");
      out.write("											  </div>\r\n");
      out.write("											</div>\r\n");
      out.write("											\r\n");
      out.write("										");
}
										
									
      out.write("\r\n");
      out.write("									\r\n");
      out.write("								</li>\r\n");
      out.write("								");
 }
							}catch(Exception e){
								
							}
						
      out.write("\r\n");
      out.write("						</ul>\r\n");
      out.write("			\r\n");
      out.write("					\r\n");
      out.write("				\r\n");
      out.write("			\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("			\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<footer style=\"background:var(--clr-1);\" class=\"text-center py-4\">\r\n");
      out.write("		<a href=\"#\" class=\"btn text-light\">@watchita</a>\r\n");
      out.write("	</footer>\r\n");
      out.write("	\r\n");
      out.write("     <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("  	<script src=\"../JS/script.js\"></script>\r\n");
      out.write("  	<script src=\"../JS/reactionCtrl.js\"></script>\r\n");
      out.write("  	<script>\r\n");
      out.write("  	\r\n");
      out.write("  		\r\n");
      out.write("  		//contorl video\r\n");
      out.write(" \r\n");
      out.write("  		\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  		\r\n");
      out.write("  		\r\n");
      out.write("  		\r\n");
      out.write("  		//control reactions  		\r\n");
      out.write("  		let likeBtn = document.querySelector(\".likeBtn\");\r\n");
      out.write("  		let likeIcon = likeBtn.querySelector(\".bi-hand-thumbs-up\");\r\n");
      out.write("  		let dislikeBtn = document.querySelector(\".dislikeBtn\");\r\n");
      out.write("  		let dislikeIcon = dislikeBtn.querySelector(\".bi-hand-thumbs-down\");\r\n");
      out.write("  		let likeCount = document.getElementById(\"likeCount\");\r\n");
      out.write("  		let dislikeCount = document.getElementById(\"dislikeCount\");\r\n");
      out.write("  		\r\n");
      out.write("  		likeBtn.onclick = function(){\r\n");
      out.write("  			if(likeIcon.classList.contains(\"bi-hand-thumbs-up\")){\r\n");
      out.write("  				likeIcon.classList.replace(\"bi-hand-thumbs-up\", \"bi-hand-thumbs-up-fill\");\r\n");
      out.write("  				likeCount.textContent = Number(likeCount.innerHTML) + 1;\r\n");
      out.write("  				\r\n");
      out.write("  				if(dislikeIcon.classList.contains(\"bi-hand-thumbs-down-fill\")){\r\n");
      out.write("  					dislikeIcon.classList.replace(\"bi-hand-thumbs-down-fill\", \"bi-hand-thumbs-down\");\r\n");
      out.write("  					dislikeCount.textContent = Number(dislikeCount.innerHTML) - 1;\r\n");
      out.write("  				}\r\n");
      out.write("  			}\r\n");
      out.write("  			else{\r\n");
      out.write("  				likeIcon.classList.replace(\"bi-hand-thumbs-up-fill\", \"bi-hand-thumbs-up\");\r\n");
      out.write("  				likeCount.textContent = Number(likeCount.innerHTML) - 1 ;\r\n");
      out.write("  			}\r\n");
      out.write("  		}\r\n");
      out.write("  		\r\n");
      out.write("  		dislikeBtn.onclick = function(){\r\n");
      out.write("  			if(dislikeIcon.classList.contains(\"bi-hand-thumbs-down\")){\r\n");
      out.write("  				dislikeIcon.classList.replace(\"bi-hand-thumbs-down\", \"bi-hand-thumbs-down-fill\");\r\n");
      out.write("  				dislikeCount.textContent = Number(dislikeCount.innerHTML) + 1;\r\n");
      out.write("  				\r\n");
      out.write("  				if(likeIcon.classList.contains(\"bi-hand-thumbs-up-fill\")){\r\n");
      out.write("  					likeIcon.classList.replace(\"bi-hand-thumbs-up-fill\", \"bi-hand-thumbs-up\");\r\n");
      out.write("  					likeCount.textContent = Number(likeCount.innerHTML) - 1 ;\r\n");
      out.write("  				}\r\n");
      out.write("  			}\r\n");
      out.write("  			else{\r\n");
      out.write("  				dislikeIcon.classList.replace(\"bi-hand-thumbs-down-fill\", \"bi-hand-thumbs-down\");\r\n");
      out.write("  				dislikeCount.textContent = Number(dislikeCount.innerHTML) - 1;\r\n");
      out.write("  			}\r\n");
      out.write("  		}\r\n");
      out.write("  		\r\n");
      out.write("  		\r\n");
      out.write("  		\r\n");
      out.write("  		\r\n");
      out.write("  		\r\n");
      out.write("  	</script>\r\n");
      out.write("  	\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
